Added smoke tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -111,3 +111,27 @@ jobs:
 
             echo "Database initialized successfully."
           EOF
+
+      - name: Run Smoke Tests
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
+            echo "Running smoke tests..."
+            cd /home/ec2-user/source-repo
+          
+            chmod +x frontend/tests/homepage.test.sh
+            ./frontend/tests/homepage.test.sh
+            if [ $? -ne 0 ]; then
+              echo "Frontend test failed!"
+              exit 1
+            fi
+            echo "Frontend test passed!"
+
+            # Run API test
+            chmod +x backend/tests/api.test.sh
+            ./backend/tests/api.test.sh
+            if [ $? -ne 0 ]; then
+              echo "Backend test failed!"
+              exit 1
+            fi
+            echo "Backend test passed!"
+          EOF
