Added Nginx

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -113,48 +113,68 @@ jobs:
             echo "Database initialized successfully."
           EOF
 
-#      - name: Run smoke tests
-#        run: |
-#          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
-#            echo "Running smoke tests..."
-#            cd /home/ec2-user/source-repo
-#
-#            chmod +x frontend/tests/homepage.test.sh
-#            ./frontend/tests/homepage.test.sh
-#            if [ $? -ne 0 ]; then
-#              echo "Frontend test failed!"
-#              exit 1
-#            fi
-#            echo "Frontend test passed!"
-#
-#            # Run API test
-#            chmod +x backend/tests/api.test.sh
-#            ./backend/tests/api.test.sh
-#            if [ $? -ne 0 ]; then
-#              echo "Backend test failed!"
-#              exit 1
-#            fi
-#            echo "Backend test passed!"
-#          EOF
+      - name: Run smoke tests
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
+            echo "Running smoke tests..."
+            cd /home/ec2-user/source-repo
 
-#      - name: Push Docker image to ECR
-#        if: success()
-#        run: |
-#          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
-#            echo "Logging in to AWS ECR.."
-#            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-#            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
-#            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
-#
-#            echo "Tagging image.."
-#            cd /home/ec2-user/infra-repo
-#            docker tag infra-repo-backend:latest ${{ secrets.AWS_ECR_REPO }}:backend-latest
-#            docker tag infra-repo-frontend:latest ${{ secrets.AWS_ECR_REPO }}:frontend-latest
-#
-#            echo "Pushing the images to ECR.."
-#            docker push ${{ secrets.AWS_ECR_REPO }}:backend-latest
-#            docker push ${{ secrets.AWS_ECR_REPO }}:frontend-latest
-#
-#            echo "Docker images pushed to ECR successfully!"
-#          EOF
+            chmod +x frontend/tests/homepage.test.sh
+            ./frontend/tests/homepage.test.sh
+            if [ $? -ne 0 ]; then
+              echo "Frontend test failed!"
+              exit 1
+            fi
+            echo "Frontend test passed!"
+
+            # Run API test
+            chmod +x backend/tests/api.test.sh
+            ./backend/tests/api.test.sh
+            if [ $? -ne 0 ]; then
+              echo "Backend test failed!"
+              exit 1
+            fi
+            echo "Backend test passed!"
+          EOF
+
+      - name: Push Docker image to ECR
+        if: success()
+        run: |
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
+            echo "Logging in to AWS ECR.."
+            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
+            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
+
+            echo "Tagging image.."
+            cd /home/ec2-user/infra-repo
+            docker tag infra-repo-backend:latest ${{ secrets.AWS_ECR_REPO }}:backend-latest
+            docker tag infra-repo-frontend:latest ${{ secrets.AWS_ECR_REPO }}:frontend-latest
+
+            echo "Pushing the images to ECR.."
+            docker push ${{ secrets.AWS_ECR_REPO }}:backend-latest
+            docker push ${{ secrets.AWS_ECR_REPO }}:frontend-latest
+
+            echo "Docker images pushed to ECR successfully!"
+          EOF
+
+      - name: Deploy to QA EC2 instance
+        run: |
+          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.QA_EC2_IP }} << EOF
+            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
+            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}
+            
+            docker pull ${{ secrets.AWS_ECR_URL }}/$ECR_REPOSITORY:backend-latest
+            docker pull ${{ secrets.AWS_ECR_URL }}/$ECR_REPOSITORY:frontend-latest
+
+            docker stop frontend backend nginx || true
+            docker rm frontend backend nginx || true
+
+            cd /home/ec2-user/infra-repo
+            docker-compose -f docker-compose.qa.yml up -d
+
+            echo "Deployment to QA EC2 successful!"
+          EOF
